name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Metrics
        id: generate-metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: nhanne249
          config_timezone: Asia/Ho_Chi_Minh
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_display: detailed
          plugin_calendar: yes
          plugin_calendar_limit: 11
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: update metrics"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          title: "Update Metrics"
          body: "This PR updates the metrics."
          labels: "metrics"
          base: main

      - name: Set file executable
        run: chmod +x /metrics/source/app/action/index.mjs

      - name: Update apt-get
        run: apt-get update

      - name: Install necessary packages
        run: |
          apt-get install -y wget gnupg ca-certificates libgconf-2-4
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update
          apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 libx11-xcb1 libxtst6 lsb-release --no-install-recommends
          apt-get install -y curl unzip
          curl -fsSL https://deno.land/x/install/install.sh | DENO_INSTALL=/usr/local sh
          apt-get install -y ruby-full git g++ cmake pkg-config libssl-dev libxml2-dev libxslt-dev
          apt-get install -y python3
          apt-get install -y build-essential patch ruby-dev zlib1g-dev liblzma-dev
          gem install licensed
          rm -rf /var/lib/apt/lists/*

      - name: Install npm packages
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Build Docker Image
        run: |
          docker build -t metrics:forked-3.34.0 .
        working-directory: ./metrics

      - name: Run Docker Container
        run: |
          docker run --rm -v $(pwd):/metrics metrics:forked-3.34.0
