name: Metrics

on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run Metrics
        id: generate-metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: nhanne249
          config_timezone: Asia/Ho_Chi_Minh
          committer_message: "chore: update metrics"
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_introduction: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_achievements: yes
          plugin_achievements_threshold: X
          plugin_achievements_display: detailed
          plugin_calendar: yes
          plugin_calendar_limit: 11
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_licenses: yes
          plugin_licenses_setup: npm ci
          plugin_skyline: yes
          plugin_skyline_year: 2022
          plugin_skyline_frames: 120
          plugin_skyline_quality: 1
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
          plugin_support: yes
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "chore: update metrics"
          committer: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
          title: "Update Metrics"
          body: "This PR updates the metrics."
          labels: "metrics"
          base: main

      - name: Build Docker Image
        run: |
          docker build -t metrics:forked-3.34.0 .
        working-directory: ./metrics

      - name: Run Docker Container
        run: |
          docker run --rm -v $(pwd):/metrics metrics:forked-3.34.0
